# Generated by Django 6.0.3 on 2026-03-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject', 'exam_year', 'exam_month')},
        ),
        migrations.AlterUniqueTogether(
            name='backlog',
            unique_together={('student', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
