# Generated by Django 6.0.3 on 2026-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_complaint_is_resolved_complaint_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Mark as True for Library/Sports — GA enforces exactly 2 sessions per week per class.'),
        ),
    ]
