# Generated by Django 6.0.3 on 2026-03-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timeslot', 'room', 'academic_year')},
        ),
    ]
