# Generated by Django 6.0.3 on 2026-03-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_consecutive_hours', models.PositiveSmallIntegerField(default=3)),
                ('mutation_rate', models.FloatField(default=0.1)),
                ('elite_percentage', models.FloatField(default=0.05, help_text='Percentage of top population to carry over')),
                ('lunch_break_period', models.PositiveSmallIntegerField(default=4, help_text='The period number that acts as lunch')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Percentage from 0 to 100')),
                ('conflict_score', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semesters_target', models.CharField(blank=True, help_text='Comma-separated semesters requested', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked slots cannot be scheduled (e.g., global lunch, maintenance)'),
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_efficiency', models.JSONField(help_text='Dictionary storing efficiency scores by department')),
                ('overall_fitness', models.FloatField()),
                ('total_teacher_gaps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='timetable.generationrequest')),
            ],
        ),
    ]
