# Generated by Django 6.0.3 on 2026-03-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_constraintconfig_generationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CSE-A, ECE-B', max_length=30, unique=True)),
                ('department', models.CharField(default='General', max_length=80)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['timeslot__day', 'timeslot__period']},
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='class_group',
            field=models.ForeignKey(blank=True, help_text='The class section this entry belongs to (e.g. CSE-A)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.classgroup'),
        ),
    ]
