# Generated by Django 6.0.3 on 2026-03-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_classgroup_alter_timetableentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='effective_date',
            field=models.DateField(blank=True, help_text='W.e.f. date shown on timetable header', null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='room_name',
            field=models.CharField(blank=True, default='', help_text='Room/Lab identifier, e.g. L-DYNAMIC', max_length=60),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_label',
            field=models.CharField(blank=True, choices=[('', 'Normal Period'), ('break', 'Break'), ('lunch', 'Lunch'), ('club', 'Club Activities')], default='', help_text='Special label: break, lunch, or club activities', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked slots cannot be scheduled'),
        ),
    ]
