# Generated by Django 6.0.3 on 2026-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='specialization_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags e.g. #Math,#Lab', max_length=255),
        ),
    ]
